url=https://www.naukri.com
username=rahman.abd23@gmail.com
password=Abdulrahman@23
resumePath=testData.Abdul_Rahman_Automation_Test_Engineer_4yrs_Exp_immediate.pdf
#resumePath=S:\\Resume_werize_latest\\Abdul_Rahman_Automation_Test_Engineer_4yrs_Exp_immediate.pdf
browser=chrome